In [1]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 2.3.4


In [2]:
# Create arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("1D array:", arr1)
print("2D array:\n", arr2)
print("Shape of arr2:", arr2.shape)
print("Dtype:", arr1.dtype)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Dtype: int64


In [3]:
# Array operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", a + b)
print("a * 2:", a * 2)
print("a.dot(b):", a.dot(b))  # dot product

a + b: [5 7 9]
a * 2: [2 4 6]
a.dot(b): 32


In [4]:
# Indexing and slicing
arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])
print("Every other:", arr[::2])


First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every other: [10 30 50]


In [5]:
# Vectorization (fast operations on entire arrays)
arr = np.array([1, 2, 3, 4, 5])
print("Original:", arr)
print("Squared:", arr ** 2)
print("Square root:", np.sqrt(arr))

# Reshaping
matrix = np.array([1, 2, 3, 4, 5, 6])
print("\nOriginal shape:", matrix.shape)
reshaped = matrix.reshape(2, 3)
print("Reshaped to (2, 3):\n", reshaped)

Original: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]

Original shape: (6,)
Reshaped to (2, 3):
 [[1 2 3]
 [4 5 6]]


In [6]:
# Statistical functions
data = np.array([10, 20, 30, 40, 50, 60, 70])
print("Data:", data)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Std dev:", np.std(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))

Data: [10 20 30 40 50 60 70]
Mean: 40.0
Median: 40.0
Std dev: 20.0
Min: 10
Max: 70
Sum: 280


In [7]:
# Useful array creation functions
zeros = np.zeros(5)
ones = np.ones((2, 3))
range_arr = np.arange(0, 10, 2)  # start, stop, step
linspace = np.linspace(0, 1, 5)  # 5 evenly spaced values from 0 to 1
random_arr = np.random.rand(5)   # 5 random values between 0 and 1

print("Zeros:", zeros)
print("Ones (2x3):\n", ones)
print("Arange:", range_arr)
print("Linspace:", linspace)
print("Random:", random_arr)

Zeros: [0. 0. 0. 0. 0.]
Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [0.60709181 0.84357055 0.08136155 0.35130858 0.16707535]
